# fly.toml app configuration file generated for primeroznl on 2023-06-11T15:34:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "primeroznl"
primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
